### ISSUE TITLE
[production][package#show] Symbol or String expected, but NilClass given.

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#8167]
package#show threw this 3 times
<pre>
Symbol or String expected, but NilClass given.
</pre>
[https://build.opensuse.org/package/show/devel:gcc/gcc33](https://build.opensuse.org/package/show/devel:gcc/gcc33)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d5f9c259df855000dda726e)

**Comment by coolo** [comment]
executive summary:

coderay crashes rendering code in markdown comments:

```
<comments project="devel:gcc" package="gcc33">
  <comment who="badshah400" when="2018-12-07 12:52:46 UTC" id="812733">@rguenther Any suggestions on how to fix builds on openSUSE 15.0 and Factory (last successful build for Factory is from more than a year old)? Thanks!&#13;
&#13;
```&#13;
make[4]: Entering directory '/home/abuild/rpmbuild/BUILD/gcc-3.3.3/obj-x86_64-suse-linux/gcc'&#13;
[  112s] ../../gcc/libgcc2.c: In function `gcov_exit':&#13;
[  112s] ../../gcc/libgcc2.c:1307: warning: unused variable `program_max_sum'&#13;
[  112s] ../../gcc/libgcc2.c:1309: warning: unused variable `program_runs'&#13;
[  112s] ../../gcc/unwind-dw2.c: In function `uw_frame_state_for':&#13;
[  112s] ../../gcc/unwind-dw2.c:953: error: dereferencing pointer to incomplete type&#13;
[  112s] ../../gcc/unwind-dw2.c: In function `amd64_frame_state_for':&#13;
[  112s] ../../gcc/unwind-dw2.c:1313: error: dereferencing pointer to incomplete type&#13;
```</comment>
</comments>

**Comment by coolo** [comment]
Regression of https://github.com/openSUSE/open-build-service/pull/8150

**Comment by hellcp** [comment]
That would be regression of #8148, which introduced coderay into the comments

**Comment by eduardoj** [comment]
#8148 is reverted in build.opensuse.org, with a monkey patch.
