### ISSUE TITLE
[production][workflows#show] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8851]
workflows#show threw this 57 times
<pre>
undefined method `each&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/staging_workflows/1](https://build.opensuse.org/staging_workflows/1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5deaabda4041630008b3c9fc)

**Comment by coolo** [comment]
this is a regression from b4802ba27ac50717a8dc7e261684be057c8452e0 - Staging:E has 11 failed checks and 0 build fails leading to `buildproblems[1..-1].each {}`. I honestly did not expect this to be nil, but rather an empty array

**Comment by coolo** [comment]
I monkeypatched a one liner - the PR above includes a larger scope solution.

**Comment by dmarcoux** [comment]
I've deployed this morning and this error is happening again since the monkey-patch is gone, the MOTD was empty. What was changed exactly?

**Comment by coolo** [comment]
Basically the code as I moved into the helper to test it

**Comment by hennevogel** [comment]
"the code" as in https://github.com/coolo/open-build-service/commit/1eb023dcba515df8eb81c0b076419931c2517d7a ?

**Comment by DimStar77** [comment]
I nuderstand IBS had the same issue yesterday and there a revert could be provided in a timely manner:

> 08:10 < fcrozat> maxlin IBS got a rollback yesterday : api-revert-b4802ba27ac50717a8dc7e261684be057c8452e0.patch


Could we have that pleasure too on OBS please?

**Comment by dmarcoux** [comment]
Fixed
