### PR TITLE
Prevent from erroring running the `dev:test_data:create task`

### PR DESCRIPTION
**Pull request by eduardoj**
Otherwise, an error like this is thrown:

```
Writing issue trackers into backend

rake aborted!
NoMethodError: undefined method `id' for nil:NilClass

  after_commit { PopulateToSphinxJob.perform_later(id: bs_request.id, model_name: :bs_request) }
                                                                 ^^^
/obs/src/api/app/models/review.rb:77:in `block in <class:Review>'
<internal:kernel>:90:in `tap'
/obs/src/api/lib/tasks/dev.rake:162:in `block (4 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:153:in `block (3 levels) in <top (required)>'
```

### CODE REVIEW

File: src/api/lib/tasks/dev.rake [hunk 1]
```diff
@@ -159,8 +159,8 @@ namespace :dev do
           source_package: leap_apache
         )
         new_package1.staging_project = sworkflow.staging_projects.first
-        new_package1.reviews << create(:review, by_project: new_package1.staging_project)
         new_package1.save
+        create(:review, by_project: new_package1.staging_project, bs_request: new_package1)
```
Comment (krauselukas) [inline src/api/lib/tasks/dev.rake:163]: @eduardoj why is this called `new_package1` if it is actually a request? confusing... but not introduced by you :)

**Review by krauselukas — APPROVED** [review]

**Review by krauselukas — APPROVED** [review]

File: src/api/lib/tasks/dev.rake (hunk 1 above)
Comment (eduardoj) [reply src/api/lib/tasks/dev.rake:163]: @krauselukas, these tests were introduced in commit feb8cd2 by @coolo. We can always ask him.
