### PR TITLE
Fix rendering requests partial on staging board

### PR DESCRIPTION
**Pull request by bgeuken**
The request_show_url helper requires a request number as parameter.
Otherwise it fails with an ActionView::Template::Error error:

  "undefined method `empty?' for 1:Integer"

This broke with ccaaef52ec15892fc26914030a62462d632f9800

### CODE REVIEW

**Comment by bgeuken** [comment]
@coolo @DavidKang @eduardoj Please review
