### ISSUE TITLE
[production][request#show] undefined method `repository_index_path' for #<#<Class:0x0000000006bdbb08>:0x00007f249de1b4c8>
Di...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6936]
request#show threw this 0 times
<pre>
undefined method `repository_index_path&#39; for #&lt;#&lt;Class:0x0000000006bdbb08&gt;:0x00007f249de1b4c8&gt;
Did you mean?  repositories_path
</pre>
[https://build.opensuse.org/request/show/188119](https://build.opensuse.org/request/show/188119)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c5cfbdc4d332a0008850058)

**Comment by dmarcoux** [comment]
Regression following changes in #6869
